# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

class TestQ1dailywiseday16():

    def setup_method(self, method):
        self.driver = webdriver.Chrome()

    def teardown_method(self, method):

        self.driver.quit()

    def test_q1dailywiseday16(self):
        self.driver.get("https://www.selenium.dev/selenium/web/web-form.html")
        self.driver.set_window_size(1280, 720)
        self.driver.find_element(By.ID, "my-text-id").send_keys("Harsh")
        self.driver.find_element(By.NAME, "my-text").send_keys("Selenium IDE Test")
        self.driver.find_element(By.CSS_SELECTOR, "input.form-control").send_keys("Testing Locators")
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        time.sleep(1)
        assert self.driver.find_element(By.XPATH, "//h1").text == "Form submitted"
        print("✅ TEST CASE PASSED: Form submitted successfully")
